# Generated by Django 4.2.13 on 2026-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes left early (from import: Early column HH:MM → total minutes)'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes arrived late (from import: Late column HH:MM → total minutes)'),
        ),
    ]
