# Generated by Django 4.2.13 on 2026-05-15 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Payroll month (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Payroll year (e.g. 2024)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ssnit_employee', models.DecimalField(decimal_places=2, default=0, help_text='Employee SSNIT contribution (5.5% of basic)', max_digits=12)),
                ('ssnit_employer', models.DecimalField(decimal_places=2, default=0, help_text='Employer SSNIT contribution (13% of basic)', max_digits=12)),
                ('tier2_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier2_employer', models.DecimalField(decimal_places=2, default=0, help_text='Employer Tier 2 contribution (5% of basic)', max_digits=12)),
                ('tier3_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier3_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=0, help_text='PAYE tax calculated using GRA tax bands', max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__employee_id'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
