# Generated by Django 5.2.14 on 2026-06-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_manager'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRunAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours for this employee for this run', max_digits=6)),
                ('additional_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Ad-hoc additional allowance amount (added to regular allowances)', max_digits=10)),
                ('additional_allowance_label', models.CharField(blank=True, help_text="Label for the ad-hoc allowance (e.g. 'Bonus', 'Housing Allowance')", max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__employee_id'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
