# Generated by Django 5.2.14 on 2026-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrunadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrunadjustment',
            name='overtime_hours',
        ),
        migrations.AddField(
            model_name='payrollrunadjustment',
            name='holiday_ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Public holiday overtime hours (2.0x rate)', max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollrunadjustment',
            name='regular_ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Regular overtime hours (1.5x rate)', max_digits=6),
        ),
    ]
