# Generated by Django 5.2.14 on 2026-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payrollrunadjustment_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='calculation_mode',
            field=models.CharField(choices=[('SALARY', 'Salary Grade'), ('TIMESHEET', 'Timesheet')], default='SALARY', help_text='SALARY: uses fixed basic salary. TIMESHEET: computes from attendance hours × hourly rate.', max_length=10),
        ),
    ]
