# Generated by Django 4.2.13 on 2026-06-04 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYETaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Band order (1 = lowest, applied first)', unique=True)),
                ('annual_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Upper annual income limit for this band. Leave blank for the top (unlimited) band.', max_digits=14, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (e.g. 0.175 for 17.5%)', max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssnit_employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.055'), help_text='Employee SSNIT contribution rate (default 5.5% = 0.0550)', max_digits=5)),
                ('ssnit_employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.130'), help_text='Employer SSNIT Tier 1 contribution rate (default 13% = 0.1300)', max_digits=5)),
                ('tier2_employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.050'), help_text='Employer NPRA Tier 2 contribution rate (default 5% = 0.0500)', max_digits=5)),
                ('tier3_employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.000'), help_text='Employee Tier 3 (Provident Fund) rate — optional', max_digits=5)),
                ('tier3_employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.000'), help_text='Employer Tier 3 (Provident Fund) rate — optional', max_digits=5)),
                ('working_days_per_month', models.PositiveSmallIntegerField(default=22, help_text='Average working days per month for hourly rate calculation')),
                ('working_hours_per_day', models.PositiveSmallIntegerField(default=8, help_text='Standard working hours per day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
    ]
