# Generated by Django 4.2.13 on 2026-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_payetaxband_payrollsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='HR Pro', help_text='Registered business / company name', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Registered business address', max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Company contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Company contact email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('tin_number', models.CharField(blank=True, help_text='GRA Tax Identification Number', max_length=30)),
                ('ssnit_number', models.CharField(blank=True, help_text='Employer SSNIT registration number', max_length=30)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (optional, for PDF headers)', null=True, upload_to='business_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profile',
            },
        ),
    ]
