# Generated by Django 5.2.14 on 2026-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_position_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='holiday_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for holiday overtime (2.0x). If blank, calculated as basic_salary / 176.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='regular_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for regular overtime (1.5x). If blank, calculated as basic_salary / 176.', max_digits=8, null=True),
        ),
    ]
