# Generated by Django 4.2.13 on 2026-06-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_position_holiday_ot_rate_position_regular_ot_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
    ]
