# Generated by Django 4.2.13 on 2026-06-04 11:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SELF_REVIEW', 'Self Review'), ('MANAGER_REVIEW', 'Manager Review'), ('HR_REVIEW', 'HR Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, help_text='Employee self-rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('manager_rating', models.PositiveSmallIntegerField(blank=True, help_text='Manager rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('final_rating', models.PositiveSmallIntegerField(blank=True, help_text='Final agreed rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_comments', models.TextField(blank=True, help_text="Employee's self-assessment narrative")),
                ('manager_comments', models.TextField(blank=True, help_text="Manager's overall comments")),
                ('hr_comments', models.TextField(blank=True, help_text='HR observations / notes')),
                ('development_plan', models.TextField(blank=True, help_text='Agreed development actions')),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='performance.performancereview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='performancereview',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.reviewcycle'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Manager / HR officer conducting the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='KPI / KRA title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial'), ('CUSTOMER', 'Customer'), ('INTERNAL', 'Internal Process'), ('LEARNING', 'Learning & Growth'), ('OPERATIONAL', 'Operational'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Relative weight of this KPI (e.g. 20 means 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('target', models.TextField(help_text='What success looks like / target value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric target (optional, for measurable KPIs)', max_digits=12, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual result achieved', max_digits=12, null=True)),
                ('achievement_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score 0-100 for this KPI', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comments', models.TextField(blank=True, help_text='Notes on how this KPI was assessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='performance.performancereview')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('cycle', 'employee')},
        ),
    ]
